Try to track down why the pip check CI complains that there's no python
Problematic trace:
Run pip install --no-deps .
2
  pip install --no-deps .
3
  pip check
4
  shell: /usr/bin/bash -l {0}
5
  env:
6
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
7
Processing /home/runner/work/ironflow/ironflow
8
  Preparing metadata (setup.py): started
9
  Preparing metadata (setup.py): finished with status 'done'
10
Building wheels for collected packages: ironflow
11
  Building wheel for ironflow (setup.py): started
12
  Building wheel for ironflow (setup.py): finished with status 'done'
13
  Created wheel for ironflow: filename=ironflow-0.post0.dev1-py3-none-any.whl size=55560 sha256=ad282a11fd6af681eed80cfd11fdea669ea0804c8d70fb94261dbeff216043ae
14
  Stored in directory: /tmp/pip-ephem-wheel-cache-90kvl1e4/wheels/0a/85/70/63efbb99f1e095cbecc81ddccb5fb5435eda2314b277677661
15
Successfully built ironflow
16
Installing collected packages: ironflow
17
Successfully installed ironflow-0.post0.dev1
18
ironflow 0.post0.dev1 requires python, which is not installed.
19
Error: Process completed with exit code 1.