Don't force the log removal if you're not allowed
It was causing a an issue for CI on windows machines, but it's really not a critical step anyhow.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pyiron.log'